### ISSUE TITLE
verify-ssl => false does nothing

### ISSUE THREAD

**Issue by wiibaa** [logstash-plugins/logstash-output-http#3]
`verify-ssl` is exposed as a config option, however there is nothing in the code for handling it, but there is a [TODO](https://github.com/logstash-plugins/logstash-output-http/blob/master/lib/logstash/outputs/http.rb#L63)

**Comment by jessegonzalez** [comment]
I have a solution here: logstash-plugins/logstash-output-http#12 with dependent FTW changes here:  jordansissel/ruby-ftw#32.

**Comment by Stono** [comment]
+1 for this merge request, please accept it and pull in as its causing a massive headache.
Unless anyone knows why logstash can't verify my ssl certificate which is in the java trusted store and used by other applications without issue?

**Comment by Stono** [comment]
I've added the CA and the primary cert and still get a self signed cert in chain error

**Comment by Stono** [comment]
FYI please be aware of self signed certificates/logstash: https://github.com/jordansissel/ruby-ftw/pull/33

**Comment by andrewvc** [comment]
This should be fixed in the latest version (1.1.0). Please upgrade and let us know if there are any issues. We've fully removed ftw and are now using manticore and the standard http client mixin for providing these options.

**Comment by suraj-kamath** [comment]
I still see the issue and other related in https://github.com/logstash-plugins/logstash-output-http/issues/21 
Logstash : 1.5.4
Http output plugin :1.1.0
java version: 1.8_60

@andrewvc any hints on why the issue still persists and how can it be solved ?
